export const data = [
  {
    id: 1,
    img: "https://www.annahar.com/ContentFiles/138411Image1.jpg?version=1547680",
    title: "nancy ajram",
    selected: false,
    albums: [
      {
        id: 1,
        img: "https://www.albumaty.com/uploads/cdnimg/bc33de23c11d7c246fa46c62266e4d14.jpg",
        title: "nancy 10",
        selected: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/FmsAAG2bk2I",
            title: "Hobbak Bi Ye'wa ",
            price: 16,
            completed: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/ziVy2m5oWpo",
            title: "Gayya Maak",
            price: 20,
            completed: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/G4qVG_FL4_s",
            title: "Salamat",
            price: 10,
            completed: false,
          },
        ],
      },
      {
        id: 2,
        img: "https://upload.wikimedia.org/wikipedia/ar/a/a6/Nancy-9-Cover.jpg",
        title: "nancy 9 (Hassa Beek)",
        selected: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/HIYqaDGCtx8",
            title: "3am Bet3alla2 Feek",
            price: 15,
            completed: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/0saIadsSEls",
            title: "Hassa Beek",
            price: 10,
            completed: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/0_0VyIqzL3g",
            title: "El Hob Zay El Watar",
            price: 18,
            completed: false,
          },
        ],
      },
      {
        id: 3,
        img: "https://angartwork.akamaized.net/?id=468777&size=640",
        title: "nancy 8",
        selected: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/sH-lc3o0cbU",
            title: "Yalla",
            price: 20,
            completed: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/bE_oFQMOt1o",
            title: "Rahent Aleik  ",
            price: 15,
            completed: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/8_t_rfG2lOc",
            title: "Mouch Fara Ktir",
            price: 10,
            completed: false,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    img: "https://angartwork.akamaized.net//webp/?id=1110474086&size=296",
    title: "Ramy Gamal",
    selected: false,
    albums: [
      {
        id: 1,
        img: "https://yt3.ggpht.com/ytc/AKedOLTGkdZO6Axj4qxLICm87B8HoNnYUEGzZxdiUVVxbg=s900-c-k-c0x00ffffff-no-rj",
        title: "Agmal Layali omry",
        selected: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/VD6PJkd6mhA",
            title: "Sa'af",
            price: 15,
            selected: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/15yx_sX3_lM",
            title: "Beehom Kolohom",
            price: 10,
            selected: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/0yCHt9qKdBk",
            title: "Elly Meshio",
            price: 18,
            selected: false,
          },
        ],
      },
      {
        id: 2,
        img: "https://upload.wikimedia.org/wikipedia/ar/8/8d/%D8%A3%D9%84%D8%A8%D9%88%D9%85_%D9%84%D9%8A%D8%A7%D9%84%D9%8A%D9%86%D8%A7.jpg",
        title: "Layalina",
        selected: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/IcZCrcAWqg0",
            title: "Bahawel Ansaky",
            price: 20,
            selected: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/yCGaNJmxi6Q",
            title: "Layalina",
            price: 15,
            selected: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/wwxe9Ozjd_A",
            title: "Te’eshy Leya  ",
            price: 10,
            selected: false,
          },
        ],
      },
      {
        id: 3,
        img: "https://i1.sndcdn.com/artworks-000174571864-fu9nyg-t500x500.jpg",
        title: " Malnash Ella Baa'd ",
        completed: false,
        songs: [
          {
            id: 1,
            song: "https://www.youtube.com/embed/SsrdMg0thoI",
            title: " Malnash Ella Baa'd  ",
            price: 16,
            completed: false,
          },
          {
            id: 2,
            song: "https://www.youtube.com/embed/uF-_B1a1sMA",
            title: "Matenseesh",
            price: 20,
            completed: false,
          },
          {
            id: 3,
            song: "https://www.youtube.com/embed/Ka8VXM4n2hM",
            title: "Mat Elly Fat ",
            price: 10,
            completed: false,
          },
        ],
      },
    ],
  },
];
